version: '3'

services:
  flaskapp:
    build: ./flaskapp-docker
    container_name: flaskapp

  nginx:
    build: ./nginx
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
    links:
      - flaskapp
