version: '3'

services:
  flaskapp:
    build: ./flaskapp-docker
    image: flaskapp:latest
    container_name: flaskapp

  nginx:
    build: ./nginx
    image: nginx:latest
    container_name: nginx
    network_mode: bridge
    ports:
      - '80:80'
