version: '3'

services:
  flaskapp:
    build: ./flaskapp-docker
#    image: flaskapp:latest
    container_name: flaskapp
    network_mode: host
#    ports:
#      - '8000:8000'

  nginx:
    build: ./nginx
    image: nginx:latest
    container_name: nginx
    network_mode: host
#    ports:
#      - '80:80'
