version: '3'

services:
  app:
    build: ./flaskapp-docker
    container_name: app
    command: ['gunicorn3', '-b', '0.0.0.0:8000', 'app:app', '--workers=5']

  nginx:
    build: ./nginx
    image: nginx:latest
    container_name: nginx
    ports:
      - '8000:80'
    links:
      - app
