version: '3'

services:
  app:
    build: ./flaskapp-docker
    container_name: app
    environment:
      - DATABASE_URL=postgresql://hello_flask:hello_flask@db:5432/hello_flask_dev
    command: ['gunicorn3', '-b', '0.0.0.0:8000', 'app:app', '--workers=5']

  nginx:
    build: ./nginx
    image: nginx:latest
    container_name: nginx
    ports:
      - '8000:80'
    links:
      - app

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev
    ports:
      - '5432:5432'

  alembic:
    build: ./
    links:
      - db
    command: "alembic upgrade head"
#    In order to run the migrations locally, add the DATABASE_URL of the app
#    service which is postgresql://hello_flask:hello_flask@db:5432/hello_flask_dev
#    to the psycopg2 like postgresql+psycopg2://hello_flask:hello_flask@db:5432/hello_flask_dev
#    and put it in the alembic.ini file equal to sqlalchemy.url and run the
#    docker-compose build --no-cache command.

volumes:
  postgres_data:
